baseurl = "/"
languageCode = "en-us"
title = "Jackie Penang Kitchen"

[params]
  description = "Introduce authentic Malaysia street food to the people of Manchester."

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
    
[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 2    
